const KEY='householdTreasuryMVP';
const empty=()=>({settings:{cash:0,reserve:150000,salary:0,salaryDay:18},assets:{bank:0,investment:0,ideco:0,other:0,liabilities:0},rules:[],events:[],overrides:[],history:[],imports:[]});
let state=empty(); const $=id=>document.getElementById(id); const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0); const iso=d=>new Date(d).toISOString().slice(0,10); const ym=d=>iso(d).slice(0,7);
function normalize(){const legacyAssets=state.assets||{};if(Array.isArray(state.wealth)&&!Array.isArray(state.history))state.history=state.wealth.map(r=>({month:r[0],bank:+r[1]||0,investment:+r[2]||0,ideco:0,liabilities:+r[3]||0,other:(+r[4]||0)-(+r[1]||0)-(+r[2]||0)+(+r[3]||0)}));if(Array.isArray(state.importHistory)&&!Array.isArray(state.imports))state.imports=state.importHistory;state.settings={...empty().settings,...state.settings};state.assets={...empty().assets,...legacyAssets,bank:legacyAssets.bank??legacyAssets.workingCash??state.settings.cash??0,other:legacyAssets.other??legacyAssets.otherBank??0,liabilities:legacyAssets.liabilities??legacyAssets.liability??0};for(const k of ['rules','events','overrides','history','imports'])if(!Array.isArray(state[k]))state[k]=[];if(!state.assets.bank&&state.settings.cash)state.assets.bank=state.settings.cash;}
function load(){try{state=JSON.parse(localStorage.getItem(KEY))||empty()}catch{state=empty()}normalize()}
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('saveStatus').textContent='ローカル保存済み';window.cloudSyncOnLocalSave?.()}
function lastDay(y,m){return new Date(y,m,0).getDate()}function ruleDate(y,m,d){return `${y}-${String(m).padStart(2,'0')}-${String(Math.min(d,lastDay(y,m))).padStart(2,'0')}`}
function generated(days=90){const from=new Date();from.setHours(0,0,0,0);const to=new Date(from);to.setDate(to.getDate()+days);let out=[...state.events];for(let d=new Date(from.getFullYear(),from.getMonth(),1);d<=to;d.setMonth(d.getMonth()+1)){const y=d.getFullYear(),m=d.getMonth()+1,month=`${y}-${String(m).padStart(2,'0')}`;for(const r of state.rules.filter(x=>x.enabled!==false)){let amount=Number(r.amount)||0;const o=state.overrides.find(x=>x.name===r.name&&x.month===month);if(o)amount=Number(o.amount)||0;out.push({id:`rule:${r.id}:${month}`,date:ruleDate(y,m,r.day||1),name:r.name,amount,type:r.type||'fixed',generated:true})}}
return out.filter(e=>e.date>=iso(from)&&e.date<=iso(to)).sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name))}
function forecast(days=90){let bal=Number(state.settings.cash)||0,low=bal,lowDate=iso(new Date()),rows=[];for(const e of generated(days)){bal+=Number(e.amount)||0;rows.push({...e,balance:bal});if(bal<low){low=bal;lowDate=e.date}}return{rows,low,lowDate,investable:Math.max(0,low-(Number(state.settings.reserve)||0))}}
function net(){const a=state.assets;return (a.bank||0)+(a.investment||0)+(a.ideco||0)+(a.other||0)-(a.liabilities||0)}
function render(){const f=forecast();$('kpiNet').textContent=yen(net());$('kpiCash').textContent=yen(state.settings.cash);$('kpiLow').textContent=yen(f.low);$('kpiLowDate').textContent=f.lowDate;$('kpiInvest').textContent=yen(f.investable);$('kpiInvest').className=f.investable>100000?'good':f.investable>0?'warn':'bad';$('safety').innerHTML=f.low>=state.settings.reserve?`最低残高は安全資金を <b>${yen(f.low-state.settings.reserve)}</b> 上回ります。`:`安全資金を <b>${yen(state.settings.reserve-f.low)}</b> 下回る見込みです。`;$('nextEvents').innerHTML=f.rows.slice(0,8).map(e=>`<div class="row"><div>${esc(e.name)}<div class="tiny">${e.date}</div></div><div class="amt ${e.amount<0?'bad':'good'}">${e.amount>0?'+':''}${yen(e.amount)}</div></div>`).join('')||'<div class="muted">予定なし</div>';const a=state.assets;$('assets').innerHTML=[['預金/流動',a.bank],['投資',a.investment],['iDeCo',a.ideco],['その他',a.other],['負債',-a.liabilities]].map(x=>`<div class="row"><span>${x[0]}</span><span class="amt">${yen(x[1])}</span></div>`).join('');$('eventsBody').innerHTML=f.rows.map(e=>`<tr><td>${e.date}</td><td>${esc(e.name)}</td><td>${esc(e.type||'')}</td><td class="${e.amount<0?'bad':'good'}">${e.amount>0?'+':''}${yen(e.amount)}</td><td>${yen(e.balance)}</td><td>${e.generated?'':`<button class="btn secondary" onclick="delEvent('${e.id}')">削除</button>`}</td></tr>`).join('');$('wealthBody').innerHTML=[...state.history].reverse().map(h=>`<tr><td>${h.month}</td><td>${yen(h.bank)}</td><td>${yen((h.investment||0)+(h.ideco||0)+(h.other||0))}</td><td>${yen(h.liabilities||0)}</td><td>${yen((h.bank||0)+(h.investment||0)+(h.ideco||0)+(h.other||0)-(h.liabilities||0))}</td></tr>`).join('');$('cash').value=state.settings.cash;$('reserve').value=state.settings.reserve;$('salary').value=state.settings.salary;$('salaryDay').value=state.settings.salaryDay;renderRules()}
function renderRules(){$('rules').innerHTML=state.rules.map((r,i)=>`<div class="row"><div><b>${esc(r.name)}</b><div class="tiny">毎月${r.day}日 · ${esc(r.type||'fixed')}</div></div><div class="controls"><span class="amt ${r.amount<0?'bad':'good'}">${yen(r.amount)}</span><button class="btn secondary" onclick="editRule(${i})">編集</button><button class="btn secondary" onclick="delRule(${i})">削除</button></div></div>`).join('')||'<div class="muted">固定費ルールなし</div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
window.delEvent=id=>{state.events=state.events.filter(e=>String(e.id)!==String(id));save();render()};window.delRule=i=>{state.rules.splice(i,1);save();render()};window.editRule=i=>{const r=state.rules[i],name=prompt('名称',r.name);if(!name)return;const day=+prompt('引落日',r.day),amount=+prompt('金額（支出はマイナス）',r.amount);if(!Number.isFinite(day)||!Number.isFinite(amount))return;Object.assign(r,{name,day,amount});save();render()};
$('addEvent').onclick=()=>{const date=prompt('日付 YYYY-MM-DD',iso(new Date()));if(!date)return;const name=prompt('内容','臨時支出');if(!name)return;const amount=+prompt('金額（支出はマイナス）','-10000');if(!Number.isFinite(amount))return;state.events.push({id:Date.now(),date,name,amount,type:'manual'});save();render()};$('addRule').onclick=()=>{const name=prompt('名称','固定費');if(!name)return;const day=+prompt('毎月何日','27'),amount=+prompt('金額（支出はマイナス）','-10000');if(!Number.isFinite(day)||!Number.isFinite(amount))return;state.rules.push({id:Date.now(),name,day,amount,type:'fixed',enabled:true});save();render()};
$('saveSettings').onclick=()=>{state.settings.cash=+$('cash').value||0;state.settings.reserve=+$('reserve').value||0;state.settings.salary=+$('salary').value||0;state.settings.salaryDay=+$('salaryDay').value||18;state.assets.bank=state.settings.cash;let r=state.rules.find(x=>x.id==='salary');if(state.settings.salary){if(!r){r={id:'salary',name:'給与',type:'income',enabled:true};state.rules.push(r)}r.day=state.settings.salaryDay;r.amount=Math.abs(state.settings.salary)}save();render()};
$('snapshot').onclick=()=>{const month=ym(new Date()),a=state.assets,s={month,bank:a.bank||state.settings.cash,investment:a.investment||0,ideco:a.ideco||0,other:a.other||0,liabilities:a.liabilities||0};state.history=state.history.filter(x=>x.month!==month);state.history.push(s);state.history.sort((a,b)=>a.month.localeCompare(b.month));save();render()};
function parse(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const sep=(lines[0].match(/\t/g)||[]).length>(lines[0].match(/,/g)||[]).length?'\t':',';return lines.map(line=>{let a=[],v='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===sep&&!q){a.push(v);v=''}else v+=c}a.push(v);return a.map(x=>x.trim())})}
function number(s){const t=String(s??'').replace(/[¥￥,\s]/g,'');return /^[-+]?\d+(\.\d+)?$/.test(t)?+t:null}function classify(name,head){const s=(name+' '+head).toLowerCase();if(/楽天.*カード|rakuten.*card/.test(s))return'楽天カード';if(/jal/.test(s))return'JALカード';if(/d.?card|dカード|docomo/.test(s))return'dカード';if(/bank|銀行|残高|入出金/.test(s))return'銀行';return'未分類'}
function readCsv(files){[...files].forEach(file=>{const r=new FileReader();r.onload=()=>{let text=new TextDecoder().decode(r.result);if((text.match(/�/g)||[]).length>1)try{text=new TextDecoder('shift-jis').decode(r.result)}catch{}const rows=parse(text),headers=rows[0]||[],body=rows.slice(1),kind=classify(file.name,headers.join(' '));let best={i:0,n:0};headers.forEach((h,i)=>{const n=body.map(x=>number(x[i])).filter(x=>x!==null).length+(/金額|請求|残高|amount/.test(h)?5:0);if(n>best.n)best={i,n}});const vals=body.map(x=>number(x[best.i])).filter(x=>x!==null),total=vals.reduce((a,b)=>a+b,0),last=vals.at(-1);state.imports.unshift({at:new Date().toISOString(),file:file.name,kind,total,last});save();const div=document.createElement('div');div.className='card';div.style.marginTop='10px';div.innerHTML=`<div class="title">${esc(file.name)} <span class="tag">${kind}</span></div><div class="row"><span>合計</span><b>${yen(total)}</b></div><div class="row"><span>最終値</span><b>${last==null?'—':yen(last)}</b></div><div class="controls">${kind==='銀行'&&last!=null?`<button class="btn" data-bank>銀行残高へ反映</button>`:''}${kind!=='銀行'&&kind!=='未分類'?`<button class="btn" data-card>今月請求額へ反映</button>`:''}</div>`;$('importResults').prepend(div);div.querySelector('[data-bank]')?.addEventListener('click',()=>{state.settings.cash=Math.abs(last);state.assets.bank=Math.abs(last);save();render()});div.querySelector('[data-card]')?.addEventListener('click',()=>{const month=ym(new Date());state.overrides=state.overrides.filter(o=>!(o.name===kind&&o.month===month));state.overrides.push({name:kind,month,amount:-Math.abs(total)});save();render()})};r.readAsArrayBuffer(file)})}
$('drop').onclick=()=>$('csvInput').click();$('csvInput').onchange=e=>readCsv(e.target.files);$('drop').ondragover=e=>e.preventDefault();$('drop').ondrop=e=>{e.preventDefault();readCsv(e.dataTransfer.files)};$('exportJson').onclick=()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='household-treasury-backup.json';a.click();URL.revokeObjectURL(a.href)};$('importJson').onclick=()=>$('jsonInput').click();$('jsonInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);normalize();save();render()}catch{alert('JSONを読み込めませんでした')}};r.readAsText(f)};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active');render()});window.getTreasuryState=()=>structuredClone(state);window.replaceTreasuryState=n=>{state=structuredClone(n);normalize();localStorage.setItem(KEY,JSON.stringify(state));render()};window.setTreasurySaveStatus=t=>$('saveStatus').textContent=t;load();render();
