(() => {
  if (window.__planningUiV79) return;
  window.__planningUiV79 = true;

  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Number(n)||0);
  const norm=s=>String(s??'').normalize('NFKC').replace(/[\s　()（）［］\[\]・\-_/\.]/g,'').toUpperCase();
  const stateNow=()=> (window.getTreasuryStateRaw||window.getTreasuryState)?.()||{};
  const model=()=>window.householdPlanningV79;
  let allTimer=null,cfTimer=null;

  function persist(st,msg){
    st.masters=st.masters||{};st.masters.updatedAt=new Date().toISOString();
    window.treasuryRecoverySnapshot?.(`${msg}直前`);window.replaceTreasuryState?.(st);window.setTreasurySaveStatus?.(`${msg}・同期中`);window.cloudSyncOnLocalSave?.();scheduleAll(100);
  }

  function ensureBaselineUi(){
    const root=$('unifiedCardsV77');if(!root)return null;let box=$('cardBaselineV79');if(box)return box;
    box=document.createElement('details');box.id='cardBaselineV79';box.style.margin='10px 0';box.innerHTML=`<summary style="cursor:pointer"><b>一括カードの予測基準</b> <span class="tag">v79</span></summary><div class="note" style="margin:8px 0">確定請求 ＞ この月だけ補正 ＞ 基準請求額 ＞ 固定費積上げ、の順でCash Flowへ反映します。基準額より利用済み＋未実績固定費が大きい場合は、判明済み金額を下限にします。</div><div id="cardBaselineRowsV79"></div>`;
    const rows=$('unifiedCardRowsV77');rows?.before(box);box.addEventListener('click',e=>{const b=e.target.closest?.('[data-v79-card-base-save]');if(!b)return;e.preventDefault();saveBaseline(b.dataset.v79CardBaseSave)});return box;
  }
  function renderBaselines(){
    const box=ensureBaselineUi(),host=$('cardBaselineRowsV79');if(!box||!host)return;const st=stateNow(),cards=(st.masters?.cards||[]).filter(c=>c.active!==false&&model()?.paymentMode?.(c)!=='REVOLVING');
    host.innerHTML=cards.length?cards.map(c=>{const base=model()?.baselineOf?.(c)||0,mode=model()?.forecastMode?.(c)||'COMPONENTS';return `<div class="card" style="padding:9px;margin-top:7px"><div class="row"><div><b>${esc(c.name||'カード')}</b><div class="tiny">${mode==='BASELINE'?`基準 ${yen(base)}`:'固定費・利用額ベース'}</div></div><div class="controls"><select data-v79-card-base-mode="${esc(String(c.id))}"><option value="BASELINE" ${mode==='BASELINE'?'selected':''}>基準額</option><option value="COMPONENTS" ${mode==='COMPONENTS'?'selected':''}>固定費積上げ</option></select><input style="width:120px" type="number" min="0" inputmode="numeric" data-v79-card-base-amount="${esc(String(c.id))}" value="${base||''}" placeholder="例 120000"><button type="button" class="btn secondary" data-v79-card-base-save="${esc(String(c.id))}">保存</button></div></div></div>`}).join(''):'<div class="muted">一括払いカードはありません。</div>';
  }
  function saveBaseline(id){const st=stateNow(),c=(st.masters?.cards||[]).find(x=>String(x.id)===String(id));if(!c)return;const key=CSS.escape(String(id)),mode=document.querySelector(`[data-v79-card-base-mode="${key}"]`)?.value||'COMPONENTS',raw=document.querySelector(`[data-v79-card-base-amount="${key}"]`)?.value??'',amount=raw===''?0:Number(raw);if(!Number.isFinite(amount)||amount<0)return alert('基準請求額を確認してください。');if(mode==='BASELINE'&&amount<=0)return alert('基準額方式では月間基準請求額を入力してください。');c.forecastMode=mode;c.forecast_mode=mode;c.monthlyBaselineAmount=Math.max(0,amount);c.updatedAt=new Date().toISOString();persist(st,'カード基準請求額保存')}

  function currentMonthTransactions(st){
    const ym=new Date().toISOString().slice(0,7),out=[];
    for(const p of st.purchaseEvents||[]){if(!String(p.purchase_date||'').startsWith(ym))continue;const econ=String(p.economic_type||'EXPENSE').toUpperCase();if(econ!=='EXPENSE')continue;out.push({date:p.purchase_date,name:p.merchant_raw||p.merchant_normalized||'カード利用',amount:Math.abs(Number(p.original_amount)||0),scope:String(p.spending_class||p.expense_scope||'NORMAL').toUpperCase(),category:p.category||'',source:p.card||'カード'})}
    for(const t of st.cashTransactions||[]){if(!String(t.date||'').startsWith(ym)||Number(t.amount)>=0)continue;const econ=String(t.economic_type||'').toUpperCase(),cf=String(t.cashflow_type||t.type||'').toUpperCase();if(econ&&econ!=='EXPENSE')continue;if(['CARD_SETTLEMENT','TRANSFER','INVESTMENT_CONTRIBUTION'].includes(cf)||t.is_transfer)continue;out.push({date:t.date,name:t.description_raw||t.description||'口座支出',amount:Math.abs(Number(t.amount)||0),scope:String(t.spending_class||t.expense_scope||t.ordinary_or_special||'NORMAL').toUpperCase(),category:t.category||'',source:t.source||'銀行'})}
    return out.sort((a,b)=>String(b.date).localeCompare(String(a.date))||String(a.name).localeCompare(String(b.name),'ja'));
  }
  function annualItems(st){return (st.masters?.fixedExpenses||[]).filter(x=>x.active!==false&&String(x.cadence||'').toUpperCase()==='ANNUAL')}
  function planHtml(item){const p=model()?.annualPlan?.(item);if(!p)return'<div class="muted">計算できません。</div>';if(!p.valid)return`<div class="note warn">${esc(p.reason||'計算条件不足')}</div>`;const bonusText=p.bonuses?.length?p.bonuses.map(b=>`${b.month}月 ${yen(b.amount)}`).join(' / '):'なし';return `<div class="row"><span>年額</span><b>${yen(p.amount)}</b></div><div class="row"><span>積立済</span><b>${yen(p.reserved)}</b></div><div class="row"><span>残必要額</span><b>${yen(p.shortage)}</b></div><div class="row"><span>ボーナス充当</span><b>${yen(p.bonusTotal)}</b></div><div class="tiny">使途: ${esc(bonusText)}</div><div class="row"><span>${p.mode==='AUTO'?'自動毎月額':'指定毎月額'}</span><b>${yen(p.regular)}</b></div><div class="tiny">計算: (${yen(p.shortage)} − ${yen(p.bonusTotal)}) ÷ ${Math.max(1,p.months.length)}か月 → ${yen(p.regular)}/月</div><details style="margin-top:7px"><summary class="tiny">月別積立内訳 ${p.schedule.length}か月</summary>${p.schedule.map(s=>`<div class="row"><span>${esc(s.ym)}</span><span><b>${yen(s.total)}</b><span class="tiny"> 毎月 ${yen(s.monthly)}${s.bonus?` + ボーナス ${yen(s.bonus)}`:''}</span></span></div>`).join('')||'<div class="muted">支払月まで積立月がありません。</div>'}</details>${p.remaining>0?`<div class="note warn" style="margin-top:7px">計画後も ${yen(p.remaining)} 不足します。</div>`:''}`}

  function ensureDashboardUi(){
    const phase=$('dashboardPhase8V39');if(!phase)return null;
    const decision=$('dashboardDecisionV39');if(decision)decision.style.display='none';const m=$('dashboardMonthV39')?.closest('.card.half');if(m)m.style.display='none';const o=$('dashboardObligationsV39')?.closest('.card.half');if(o)o.style.display='none';
    let root=$('dashboardPlanningV79');if(root)return root;root=document.createElement('div');root.id='dashboardPlanningV79';root.className='grid';root.style.marginTop='12px';root.innerHTML=`<div class="card full"><div class="title">最低残高レンジ <span class="tag">v79</span></div><div id="dashMinimaV79" class="form" style="margin-top:8px"></div></div><div class="card half"><div class="title">今月の支出</div><div id="dashSpendV79"></div></div><div class="card half"><div class="title">年払い・ボーナス使途</div><div id="dashAnnualV79"></div></div><div class="card full"><div class="title">月別収支（年払い積立後）</div><div id="dashFlowV79"></div></div>`;decision?.after(root);return root;
  }
  function renderDashboard79(){
    if(!ensureDashboardUi())return;const st=stateNow();let f30={},f60={},f90={},f180={},salary={};try{f30=forecast(30);f60=forecast(60);f90=forecast(90);f180=forecast(180);salary=forecastUntil(nextSalaryDate())}catch{}
    const minima=[['次の給与まで最低',salary.low,salary.lowDate],['1か月最低',f30.low,f30.lowDate],['2か月最低',f60.low,f60.lowDate],['3か月最低',f90.low,f90.lowDate],['6か月最低',f180.low,f180.lowDate]];
    $('dashMinimaV79').innerHTML=minima.map(([k,v,d])=>`<div><span class="muted">${k}</span><b class="${Number(v)<0?'bad':''}" style="display:block;font-size:20px;margin-top:5px">${yen(v)}</b><div class="tiny">最低日 ${esc(d||'—')}</div></div>`).join('');
    const tx=currentMonthTransactions(st),ordinary=tx.filter(x=>x.scope!=='SPECIAL').reduce((a,x)=>a+x.amount,0),special=tx.filter(x=>x.scope==='SPECIAL').reduce((a,x)=>a+x.amount,0);
    $('dashSpendV79').innerHTML=`<div class="row"><span>通常支出</span><b>${yen(ordinary)}</b></div><div class="row"><span>特別費</span><b>${yen(special)}</b></div><div class="row"><span>合計</span><b>${yen(ordinary+special)}</b></div><details style="margin-top:8px"><summary class="btn secondary" style="cursor:pointer;display:inline-block">その場で内訳を見る ${tx.length}件</summary><div style="margin-top:7px">${tx.map(x=>`<div class="row" style="align-items:flex-start"><div><b>${esc(x.name)}</b><div class="tiny">${esc(x.date)} · ${esc(x.source)}${x.category?` · ${esc(x.category)}`:''}</div></div><b>${yen(x.amount)}</b></div>`).join('')||'<div class="muted">今月の支出明細はありません。</div>'}</div></details>`;
    const annual=annualItems(st);$('dashAnnualV79').innerHTML=annual.length?annual.map(item=>{const p=model()?.annualPlan?.(item);return `<details class="card" style="padding:9px;margin-top:7px"><summary style="cursor:pointer;display:flex;justify-content:space-between;gap:8px"><span><b>${esc(item.name||'年払い')}</b><span class="tiny"> ${p?.targetYear||''}年${p?.dueMonth||''}月</span></span><b>${yen(item.amount)}</b></summary><div style="margin-top:7px">${planHtml(item)}</div></details>`}).join(''):'<div class="muted">年払い項目はありません。</div>';
    let flow=null;try{flow=window.householdEffectiveFlowV41?.()}catch{}const rows=flow?.rows||[];$('dashFlowV79').innerHTML=rows.length?`<div class="table"><table style="min-width:620px"><thead><tr><th>月</th><th>収入</th><th>支出</th><th>表面収支</th><th>年払い積立</th><th>積立後収支</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i===0?'今月残り':esc(r.ym)}</td><td class="good">${yen(r.income)}</td><td class="bad">${yen(r.outflow)}</td><td class="${r.cashFlow>=0?'good':'bad'}">${yen(r.cashFlow)}</td><td>${yen(r.reserveNeed)}</td><td class="${r.effective>=0?'good':'bad'}"><b>${yen(r.effective)}</b></td></tr>`).join('')}</tbody></table></div>`:'<div class="muted">月別収支を計算できませんでした。</div>';
  }

  function readAnnualBox(box){const val=s=>box.querySelector(s)?.value??'',num=s=>{const v=val(s);return v===''?0:Number(v)},bonuses=[];for(const n of [1,2]){const m=Number(val(`[data-f-bm${n}]`)),a=Number(val(`[data-f-ba${n}]`));if(m>=1&&m<=12&&a>0)bonuses.push({month:m,amount:a})}return{amount:Math.max(0,num('[data-f-amount]')),dueMonth:Number(val('[data-f-due-month]'))||null,reservedAmount:Math.max(0,num('[data-f-reserved]')),reserveMode:val('[data-f-mode]')||'AUTO',monthlyReserveAmount:Math.max(0,num('[data-f-monthly]')),bonusAllocations:bonuses}}
  function renderAnnualCalc(box,fillAuto=false){if(!box)return;const item=readAnnualBox(box),p=model()?.annualPlan?.(item),out=box.querySelector('[data-v79-annual-output]');if(!p||!out)return;if(fillAuto&&p.valid&&item.reserveMode==='AUTO'){const f=box.querySelector('[data-f-monthly]');if(f)f.value=String(p.regular)}out.innerHTML=planHtml({...item,monthlyReserveAmount:item.reserveMode==='AUTO'?p.regular:item.monthlyReserveAmount})}
  function enhanceAnnualBoxes(){document.querySelectorAll('#semanticFixedRowsV48 [data-v48-fixed]').forEach(box=>{if(box.querySelector('[data-f-cad]')?.value!=='ANNUAL')return;if(box.querySelector('[data-v79-annual-panel]'))return;const p=document.createElement('div');p.dataset.v79AnnualPanel='1';p.className='card';p.style.cssText='padding:10px;margin-top:9px';p.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><div><b>年払い計算</b><div class="tiny">自動では、ボーナス充当後の残額を支払月までの月数で割ります。</div></div><button type="button" class="btn secondary" data-v79-annual-calc>計算</button></div><div data-v79-annual-output style="margin-top:7px"></div>`;box.appendChild(p);renderAnnualCalc(box,true)})}

  function kindMeta(r){const t=String(r?.type||''),src=String(r?.source||'');if(t==='CARD_REVOLVING_PAYMENT'||src==='card_revolving_v66')return{kind:'REVOLVING',card:r.card||'',ym:r.billing_month||String(r.date||'').slice(0,7)};if(t==='CARD_ESTIMATE'||src==='card_estimate_v49'||src==='card_estimate_v79')return{kind:'ESTIMATE',card:r.card||'',ym:r.billing_month||String(r.date||'').slice(0,7)};if(t==='CARD_SETTLEMENT'||src==='card_settlement')return{kind:'ACTUAL',card:r.card||String(r.name||'').replace(/カード支払.*/,''),ym:String(r.date||'').slice(0,7)};return null}
  function patchCardEditButtons(){const active=Number(document.querySelector('#mobileCashflowV60 [data-v60-h].active')?.dataset.v60H)||30;let rows=[];try{rows=forecast(active).rows||[]}catch{}const byId=new Map(rows.map(r=>[String(r.id||''),r]));document.querySelectorAll('#mobileCashflowRowsV60 .v60-row[data-v70-row]').forEach(el=>{if(el.querySelector('[data-v75-card-edit]'))return;const r=byId.get(String(el.dataset.v70Row||'')),m=kindMeta(r);if(!m)return;const actions=el.querySelector('.v70-actions');if(!actions)return;const label=m.kind==='REVOLVING'?'この月の返済額を編集':m.kind==='ACTUAL'?'請求を編集':'この月の見込を編集';actions.insertAdjacentHTML('beforeend',`<button type="button" class="btn secondary" data-v75-card-edit data-v75-kind="${esc(m.kind)}" data-v75-card="${esc(m.card)}" data-v75-ym="${esc(m.ym)}">${label}</button>`)})}
  function stabilizeCashflow(){const page=$('cashflow');if(!page?.classList.contains('active'))return;const grid=page.querySelector('.grid'),chart=$('cashflowForecastChartV21');if(grid&&chart&&grid.firstElementChild!==chart)grid.prepend(chart);const h=Number(document.querySelector('#mobileCashflowV60 [data-v60-h].active')?.dataset.v60H)||Number($('forecastHorizon')?.value)||30;if($('forecastHorizon'))$('forecastHorizon').value=String(h);try{window.renderCashflowChartV21?.()}catch{}patchCardEditButtons()}

  function scheduleCashflow(ms=80){clearTimeout(cfTimer);cfTimer=setTimeout(stabilizeCashflow,ms)}
  function scheduleAll(ms=100){clearTimeout(allTimer);allTimer=setTimeout(()=>{renderBaselines();renderDashboard79();enhanceAnnualBoxes();scheduleCashflow(40)},ms)}

  document.addEventListener('click',e=>{const calc=e.target.closest?.('[data-v79-annual-calc]');if(calc){e.preventDefault();const box=calc.closest('[data-v48-fixed]');return renderAnnualCalc(box,true)}if(e.target.closest?.('[data-v60-h],[data-page="cashflow"]'))scheduleCashflow(70);if(e.target.closest?.('[data-page="dashboard"],[data-page="settings"]'))scheduleAll(100)},false);
  document.addEventListener('change',e=>{const box=e.target.closest?.('[data-v48-fixed]');if(box&&box.querySelector('[data-f-cad]')?.value==='ANNUAL'&&e.target.matches('[data-f-amount],[data-f-due-month],[data-f-reserved],[data-f-mode],[data-f-monthly],[data-f-bm1],[data-f-ba1],[data-f-bm2],[data-f-ba2]')){if(box.querySelector('[data-f-mode]')?.value==='AUTO')renderAnnualCalc(box,true);else renderAnnualCalc(box,false)}},false);
  window.addEventListener('treasury:pagechange',e=>{const p=e?.detail?.page;if(p==='cashflow')scheduleCashflow(90);if(p==='dashboard'||p==='settings')scheduleAll(120)});
  const prevReplace=window.replaceTreasuryState;if(typeof prevReplace==='function'&&!window.__planningUiReplaceV79){window.__planningUiReplaceV79=true;window.replaceTreasuryState=function(n){const r=prevReplace(n);scheduleAll(120);return r}}
  window.addEventListener('pageshow',()=>scheduleAll(180));setTimeout(()=>scheduleAll(220),0);
  window.householdPlanningUiV79={renderBaselines,renderDashboard79,enhanceAnnualBoxes,stabilizeCashflow};
})();
