// supersedes household-treasury-v88-card-settings-stability
// regression-compat: household-treasury-v87-revolving-payoff-cap
// regression-compat: household-treasury-v86-card-consistency
// regression-compat: household-treasury-v85-asset-snapshot
// regression-compat: household-treasury-v84-transfer-actions
// regression-compat: household-treasury-v83-account-transfer
// regression-compat: household-treasury-v82-liquidity-flow
// regression-compat: household-treasury-v81-card-cycle-bank-dashboard
// regression-compat: household-treasury-v80-annual-baseline
// regression-compat: household-treasury-v79-planning-stability
// regression-compat: household-treasury-v77-card-settings
const CACHE="household-treasury-v89-mobile-90-day-default";
const CORE=["./index.html","./manifest.webmanifest","./app.js?v=8","./import-history-hotfix.js?v=11","./event-yucho-v13.js?v=14","./adhoc-events-v15.js?v=15","./bank-chart-v20.js?v=20","./cashflow-chart-v21.js?v=21","./recovery-safety.js?v=11","./sync-state-sanitizer-v22.js?v=22","./storage-budget-v55.js?v=55","./master-manager-v27.js?v=27","./card-settings-unified-v77.js?v=77","./import-engine-v28.js?v=28","./csv-parser-v73.js?v=73","./asset-snapshot-v85.js?v=85","./date-normalizer-v75.js?v=75","./mobile-import-v73.js?v=73","./mufg-import-integrity-v65.js?v=65","./phase2-reconcile-ui-v29.js?v=29","./link-audit-v33.js?v=33","./reimbursement-v35.js?v=35","./mobile-runtime-gate-v72.js?v=72","./future-planner-v37.js?v=37","./forecast-v38.js?v=38","./dashboard-v39.js?v=39","./cashflow-integration-v41.js?v=41","./payment-routing-v42.js?v=42","./fixed-master-unified-v43.js?v=43","./kabu-card-v44.js?v=44","./settings-ux-v45.js?v=45","./card-autolink-v46.js?v=46","./observer-guard-v50.js?v=50","./semantic-model-v47.js?v=47","./mufg-card-semantics-v75.js?v=75","./semantic-observer-guard-v71.js?v=71","./semantic-ui-v48.js?v=48","./semantic-review-stability-v76.js?v=76","./card-identity-v51.js?v=51","./card-forecast-v49.js?v=49","./settings-reactive-v53.js?v=53","./settings-list-integrity-v54.js?v=54","./rakuten-billing-v56.js?v=56","./card-import-corrections-v73.js?v=73","./rakuten-enavi-v74.js?v=74","./integrity-hotfix-v57.js?v=57","./bonus-allocation-v58.js?v=58","./bonus-allocation-target-fix-v58.js?v=58","./mobile-cashflow-v59.js?v=59","./mobile-host-v70.js?v=89","./occurrence-card-bridge-v65.js?v=65","./audit-hardening-v65.js?v=65","./revolving-card-v66.js?v=66","./bonus-modal-stability-v67.js?v=67","./mobile-interaction-v70.js?v=78","./card-cashflow-edit-v75.js?v=75","./desktop-interaction-v69.js?v=69","./tab-router-v71.js?v=71","./planning-model-v79.js?v=79","./planning-ui-v79.js?v=79","./planning-model-v80.js?v=80","./planning-ui-v80.js?v=80","./card-cycle-v81.js?v=81","./card-cycle-ui-v81.js?v=81","./dashboard-bank-v81.js?v=81","./card-event-consistency-v86.js?v=86","./import-review-cleanup-v82.js?v=82","./account-transfer-v83.js?v=83","./account-transfer-actions-v84.js?v=84","./revolving-payoff-cap-v87.js?v=87","./card-settings-stability-v88.js?v=88","./sync-v26.js?v=26","./sync-v24.js?v=57","./icons/icon.svg"];
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",e=>{if(e.request.method!=="GET")return;const u=new URL(e.request.url);if(u.origin!==location.origin)return;e.respondWith(fetch(e.request,{cache:'no-store'}).then(resp=>{if(resp&&resp.ok){const cp=resp.clone();caches.open(CACHE).then(c=>c.put(e.request,cp))}return resp}).catch(async()=>{const exact=await caches.match(e.request);if(exact)return exact;if(e.request.mode==="navigate")return caches.match("./index.html");return Response.error()}))});